getgauge/gauge

- gauge.go
Greetings fellow ThoughtWorkers!
More expressive output relating to #128
Also move version up the flag hierarchy because program can exit before
doing any additional work.
> Improve version flag output

- version.go
- version_test.go
Create a `versionError` function to reduce verbosity
Prior to this fix version was reporting incorrect errors due to wrong indexes.
Tests now use more idiomatic matchers
> Refactor version.go and bugfix

- README.md
Current link is broken; fixed to link to the correct page on the documentation.
> Fixed Test Code link in README

- execution/rerun/rerun.go
- gauge.go
- Wrap `runner.SetFlags()` in `runner.Initialize()`.
- `runner.Initialize()` returns returns error if `--failed` flag is set, but no previous failures are found
- `main()` calls `runner.Initialize()` and exits if it returns an error.
This addresses #418. Putting it up for code review suggestions.
> Don't run default specs if --failed is run with no previous failures

- execution/stream/stream.go
- execution/stream/stream_test.go
- filter/filter.go
- filter/specsFilter.go
- gauge.go
- gauge/specCollection.go
- gauge/specCollection_test.go
- parser/parse.go
- parser/parse_test.go
- parser/testdata/sample2.spec
Added a flag `--order`.
It accepts two values `sort` and `random`.
If the flag is not specified the order mentioned by user/obtained from file system is maintained.
> #641 Adding order flag

- Godeps/Godeps.json
- analytics/analyze.go
- api/apiMessageHandler.go
- config/configuration.go
- config/configuration_test.go
- gauge.go
- skel/gauge.properties
- skel/gen.go
- track/track.go
- generate a unique UUID per install. #653 
- track and send anonymous events to GA, #658
> introduce install ID, capture anonymous usage stats. #658

- filter/specItemFilter.go
- filter/specItemFilter_test.go
- parser/parse.go
- parser/parse_test.go
- Collecting all files before parsing specs.
- De-duplication of specs is happens while collection of specs.
- Scenario indexes are stored. After parsing if there are indexed spec files, the scenarios are filtered.
> De-duplicating specs given before parsing.

- api/lang/completion.go
- api/lang/completion_test.go
- api/lang/file.go
- api/lang/server.go
Fixing bugs on #718 
- Completion item list will give parameters with spaces if given user invokes autocomplete with only `*`. If the autocomplete is invoked with `*` and a space, the list will not have a space at start.
- The autocomplete will automatically add a space after `*` if user has not given one already.
- Added a document text cache for all open files.
> LSP Code completion should handle spaces

- api/infoGatherer/specDetails.go
- api/infoGatherer/specDetails_test.go
- api/lang/completion.go
- api/lang/completion_test.go
- api/lang/file.go
- gauge/arg.go
- parser/parse.go
- parser/specparser.go
- parser/specparser_test.go
- completion shows only if the cursor is in between a step
- completion doesn't show up if cursor is in between parameters 
- duplicate steps are filtered
- completion replaces the text (after *) entered by the user.
> improvements on LSP support for code completion

- .travis.yml
- cmd/telemetry.go
- GAUGE_TELEMETRY_ENABLED env var will override `gauge telemetry` and control the toggle.
- print message when GAUGE_TELEMETRY_ENABLED is set.
> allow telemetry to be overridden via env var, #736

- CONTRIBUTING.md
Previous link is obsolete,  new link is https://github.com/getgauge/gauge/wiki/Gauge-Technical-Documentation
> updating Developer Documentation link to newer URL

- api/lang/server.go
- cmd/cmd.go
- logger/logger.go
Custom logger doesn't print to standard output instead sends log message to custom logger
LSP uses this custom logger to send `window/logMessage` to lsp client.
> adding custom logger

- api/lang/rename.go
- api/lang/runner.go
- api/lang/server.go
- Added client capability which checks if client supports `workspace/saveFiles` request before sending the request to client.
- `workspace/saveFiles` request is sent before refactoring.
- refactoring parsing the file to get step text. This is needed as there seems to be some lag for the spec cache to update.
> Sending workspace/saveFiles request to client before refactoring

- api/lang/server.go
- api/lang/telemetry.go
- cmd/cmd.go
- cmd/daemon.go
- cmd/version.go
- track/track.go
- do not print telemetry message for `version` and `daemon` subcommands
- prompt the user about telemetry via lsp
ref https://github.com/getgauge/gauge-vscode/issues/283
> Lsp telemetry message

- cmd/run.go
- cmd/run_test.go
- execution/execute.go
- failures return non-zero exit code by default
- override this by passing `--no-exit-code` flag to `run`
> add --no-exit-code flag to run, #1126

- cmd/run.go
- cmd/run_test.go
- execution/execute.go
- execution/exitcode.go
do not override fail-safe for parse errors, #1154
> rename: no-exit-code to fail-safe

- cmd/run.go
- cmd/run_test.go
- execution/rerun/rerun.go
log level can now be overridden in `--failed` and `--rerun` user flows.
> 1112 log level override

- build/npm/.gitignore
- build/npm/README.md
- build/npm/package.json
- build/npm/src/index.js
- build/npm/src/install.js
- build/npm/test/test.js
publishes a npm installer to `@getgauge/cli`
version has been removed from `package.json`. this needs a `npm version <version>` before running `npm publish`
pipeline has been set for this.
> add npm installer for gauge, #1157

- build/install/windows/gauge-install.nsi
- Also installs html-report plugin by default.
> Adding python, javascript and dotnet runners to windows installer, #1193

- env/env.go
- env/env_test.go
- execution/result/suiteResult.go
Report always shows `Environment: default` regardless the env passed into the `gauge run`.
This PR attempts to fix that issue.
> fixed environment values population

- conn/connectionHandler.go
- execution/parallelExecution_test.go
- execution/specExecutor_test.go
- runner/grpcRunner.go
- runner/runner.go
- validation/validation_test.go
exit gauge on runner connection close. this will prevent gauge from executing steps once it's connection is closed (abnormally).
> 1158 exit on runner crash

- build/npm/src/index.js
We use gauge in our CI environment to control our end to end tests. Unfortunately the npm install sometimes has an error during the download. Because of the lack of return npm does not realise that there has been an error and therefore exits with a 0. This causes our build to continue and to attempt to use gauge when the binary isn't available.
This fix is intended to make the failure to download as part of the install script recognised by npm and therefore exit with the correct status.
> Ensure that errors from post install propagate to npm

- gauge/arg.go
- gauge/arg_test.go
In the function `AddArgValue`, the `stepArg.Name` is lost since `stepArg` is re-assigned while assigning the value of it. This commit ensures it is assigned back. 
If `name` of argument is not set, the result received by reporting plugins will have name for it's step parameter as empty. As a result, it cannot be mapped to placeholder in step text.
> Retain name of arg while setting arg value

- env/env.go
- env/env_test.go
Fix for #1333 
This is an initial PR to set `gauge_environment` variable. The language runner could then use this to expose in the API.
> Sets gauge environment variable based on selected env

- cmd/cmd.go
- cmd/run.go
- execution/execute.go
- execution/specExecutor.go
- execution/specExecutor_test.go
- filter/specItemFilter.go
- filter/specItemFilter_test.go
It's kinda like feature request.
Added flag to set max retries for failed scenarios. It could be useful when we have unstable tests which depends on external conditions like internet stability or 3rd-party services.
For example, test may fails because there was bad network conditions and request took too much time.
How it will work:
**Given scenario:**
```
|num|
|  0|
| 10|
* Given <num> equals to 10
```
**When execute:**
`gauge run specs/ --max-retries-count 2`
**Then output:**
```
|num|
|---|
|0  |
Failed Step: Given <num> equals to 10
Specification: specs/example.spec:8
Error Message: AssertionError [ERR_ASSERTION]: '0' == '10'
Stacktrace: 
AssertionError [ERR_ASSERTION]: '0' == '10'
at Object.<anonymous> (tests/step_implementation.js:8:10)
|num|
|---|
|0  |
Failed Step: Given <num> …
```
> Added flag to set max retries count for failed scenario

- plugin/plugin.go
plugin kill timer should have PluginKillTimeout instead of PluginConnectionTimeout.
> Fixed plugin kill timer

- cmd/init.go
The "list-templates" subcommand has been removed via https://github.com/getgauge/gauge/issues/693
in favor of a "-t/--templates" flag to the "init" subcommand.
Old usage: `gauge list-templates`
New usage: `gauge init --templates`
Closes #1543
> Fix suggestion to use nonexistent "list-templates" subcommand

- .github/workflows/release.yml
- build/create_release_text.rb
For example.
```
➜ ruby build/create_release_text.rb getgauge invalid
Traceback (most recent call last):
build/create_release_text.rb:69:in `<main>':  (RuntimeError)
Could not fetch release information for github repo: 
https://github.com/getgauge/invalid
Please check the if this is valid repo
➜ ✗ 
```
Also fix the workflow script to pass the right order of parameter
> Fix release script error handling

- env/env.go
- env/env_test.go
- util/fileUtils.go
- util/fileUtils_test.go
set `gauge_spec_file_extensions=<comma separated val>` to define valid gauge spec file extensions.
If the above is not set, gauge shall default to `.spec` and `.md` as valid extensions (keeping current behaviour)
> allow spec file extensions to be configured, fixes #1599

- parser/parse_test.go
- util/fileUtils.go
- util/fileUtils_test.go
- version/version.go
> Exit with proper status code when specs dir is empty or doesn't exists.

- build/npm/package-lock.json
- build/npm/package.json
- build/npm/src/index.js
- build/npm/src/install.js
- build/npm/test/test.js
fixes #1631
- removed `request` dependency as it is deprecated. use `superagent` instead.
> use public urls to download gauge for npm install

- parser/dataTableSpecs.go
- parser/dataTableSpecs_test.go
Fixes #1585
Signed-off-by: Dharmendra Singh <dharmenn@thoughtworks.com>
> Fixe for data driven execution when scenario data table are used with parallel tag filters.

- plugin/install/install.go
Fixes: #1583
```
gauge install invalidplugin
Failed to install plugin 'jasldja'.
Reason: Invalid plugin. Could not download invalidplugin.json file.
```
When offline
```
gauge install java
Failed to install plugin 'java'.
Reason: Invalid plugin. Could not download java-install.json file.
```
```
gauge install invalid
Failed to install plugin 'invalid'.
Reason: Invalid plugin name or there's a network issue while fetching plugin details.
```
while offline
```
gauge install java
Failed to install plugin 'java'.
Reason: Invalid plugin name or there's a network issue while fetching plugin details.
```
> Improve plugin download failure message

- projectInit/init.go
- template/template.go
- template/template_test.go
Make the case consistent with other error messages
```
$ gauge init js_simple
Error ----------------------------------
[Gauge]
failed to initialize project. cannot find a Gauge template 'js_simple'
```
```
Error ----------------------------------
$ gauge init js_simple
[Gauge]
Failed to initialize project. Cannot find Gauge template 'js_simple'
```
> Fix case of template download failure message

- cmd/run.go
- go.mod
- go.sum
- vendor/github.com/getgauge/common/common.go
- vendor/modules.txt
Fixes: #555
```
$ gauge init js_simple
$ mv manifest.json manifest.json.old
$ gauge run specs
Failed to find project directory
Usage:
gauge run [flags] [args]
Examples:
gauge run specs/
gauge run --tags "login" -s -p specs/
Flags:
-e, --env string              Specifies the environment to use (default "default")
--fail-safe               Force return 0 exit code, even in case of failures.
-f, --failed                  Run only the scenarios failed in previous run. This cannot be used in conjunction with any other argument
-g, --group int               Specify which group of specification to execute based on -n flag (default -1)
-h, --help                    Help for run
--hide-suggestion         Hide step implementation stub for every unimplemented step
-i, --install-plugins …
```
> Do not print usage when manifest file is missing

- build/npm/bin/DO_NOT_DELETE.txt
- build/npm/src/index.js
- version/version.go
required for npm link
to test:
- clone and checkout this PR
- `cd npm i <path_to_gauge_code>/build/npm`
- run `npm version 1.1.2` (or set any version of gauge to be installed)
- `cd <some work dir>`
- run `npm i <path_to_gauge_code>/build/npm`
- `node_modules/.bin/gauge -v` should print gauge version
> add a placeholder npm/bin/gauge

- gauge.go
Fix error message typo and use a calmer word
instead of panic
> Fix typo and use calmer message

- execution/simpleExecution.go
fixes https://github.com/getgauge/gauge-js/issues/395
> add current execution info in simple execution

- env/env.go
- env/env_test.go
Following this change https://github.com/getgauge/gauge/commit/4151d5b48c3973d5d569c565874fa715ce2bf86e
We no longer ignore env var if its set to an empty string.
This change is allow the value from properties file when env var value is an empty string
> Fixes an issue with env variable is to empty string

- .github/workflows/golangci-lint.yml
- api/lang/diagnostics.go
- api/lang/references.go
- api/lang/references_test.go
- cmd/run.go
- execution/merge.go
- execution/result/specResult.go
- gauge/protoConverters.go
- go.sum
- logger/logger_test.go
- parser/dataTableSpecs.go
- runner/grpcRunner.go
- validation/validate.go
- validation/validation_test.go
- version/version.go
> Fix params type for step ref request.

- build/make.go
- build/npm/package-lock.json
- build/npm/src/install.js
- build/pip/setup.tmpl
- go.mod
- go.sum
- version/version.go
This PR adds support for the Apple Silicon.
I'm not familiar with the different packaging options you are providing. Would really appreciate any hints what else needs to be changed.
> Added support for Apple Silicon. Fixes #1997

- .github/workflows/release.yml
> remove code signing from GH actions

- plugin/install/install.go
- version/version.go
Plugins, so far, are either platform independent or only support `x86` and `x86_64` arch.
This PR adds plugins targetting `arm64` to be installed.
> add arm64 plugin support

- env/env.go
- env/env_test.go
- filter/specItemFilter.go
- filter/specItemFilter_test.go
- parser/parse.go
- validation/validate.go
- version/version.go
Signed-off-by: Haroon Sheikh <haroon.sheikh@outlook.com>
> Ability to filter with case insensitive tags

- env/env.go
- parser/convert.go
- parser/specparser_test.go
- util/fileUtils.go
- util/fileUtils_test.go
allow csv/txt data files to be in subdirectory, configured by gauge_data_dir
fixes #2046
> introduce gauge_data_dir

- plugin/plugin.go
- version/version.go
Prior to this commit running a documentation plugin resulted in a zero
exit code even if the plugin explicitly returned an error. This meant
that in a CI/CD pipeline, for instance, the pipeline couldn't check the
exit code and instead had to check the console or log output, which was
brittle.
Fixes #2080
Signed-off-by: John Boyes <154404+johnboyes@users.noreply.github.com>
> Exit with non-zero code if docs plugin has error

- .github/workflows/benchmark.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/golangci-lint.yml
- .github/workflows/release.yml
- .github/workflows/tests.yml
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
[Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
Restrict the GitHub token permissions only to the required ones; this way, even if the attackers will succeed in compromising your workflow, they won’t be able to do much.
Signed-off-by: naveensrinivasan <172697+naveensrinivasan@users.noreply.github.com>
> Set permissions for GitHub actions

- build/download.sh
- conn/network_test.go
fixes #2285
Signed-off-by: Srikanth <srikanth.ddit@gmail.com>
> add support for downloading arm64 binaries

- build/brew/create_brew_pr.sh
Signed-off-by: Haroon Sheikh <haroon.sheikh@outlook.com>
> Replacing deprecated hub with gh cli

- .github/workflows/tests.yml
- CONTRIBUTING.md
- env/env.go
- util/_testdata/proj1/env/multipleSpecs/multipleSpecs.properties
- util/fileUtils.go
- util/fileUtils_test.go
- util/util.go
- util/util_test.go
- version/version.go
Fixes https://github.com/getgauge/gauge/issues/2311
By default, gauge searches with both `<project root>` and `gauge_specs_dir` for searching and validating the concepts. 
This change is adding a new `gauge_concepts_dir` property so that so we can limit the concepts validation to specific directories. If this isn't set, then current behaviour applies for backward compatibility.
Documentation: https://github.com/getgauge/docs.gauge.org/pull/338
> Adds gauge_concepts_dir for defining concepts directory 

- filter/specItemFilter_test.go
- util/fileUtils_test.go
- util/util_test.go
Changes:
- Uncomments a unit test failing due to the use of os.Clearenv()
- Removes the use of os.Clearenv() from the utils package
> Uncomments out a fixed unit test

- go.mod
- go.sum
- skel/plugin.go
- version/version.go
Fixes https://github.com/getgauge/gauge/issues/2186
- Removes screenshot plugin from required plugins
- Require screenshot plugin only when `screenshot_on_failure = true` variable is set
> Only install screenshot plugin when screenshot_on_failure is enabled

- build/npm/src/index.js
- version/version.go
This is a fix for #2332 for node v20, see https://github.com/getgauge/gauge/pull/2332#issuecomment-1608649427
In node v20 the process hangs until the request times out caused by not consumed response data. Users might get the impression that the installation fails. This behavior is not observable for node v18, v16, v14, v12, v10.
From [nodes docs](https://nodejs.org/api/http.html#class-httpclientrequest):
> if a ['response'](https://nodejs.org/api/http.html#event-response) event handler is added, then the data from the response object must be consumed, either by calling `response.read()` whenever there is a 'readable' event, or by adding a 'data' handler, or by calling the `.resume()` method
This PR fixes the installation delay by adding `res.resume()` calls.
How to reproduce:
Output for …
> Fix download timeout on node v20 install

- .github/workflows/release.yml
- build/brew/create_brew_pr.sh
Oof, the release [workflow failed](https://github.com/getgauge/gauge/actions/runs/6652744383) so it's a mess.
* GitHub [release failed](https://github.com/getgauge/gauge/actions/runs/6652744383/job/18077911869) as `hub` is gone now: https://github.com/actions/runner-images/issues/8362 - need to 
* migrate to `gh` (which this PR does). See [gh release upload](https://cli.github.com/manual/gh_release_upload).
* OR re-install via `sudo apt-get update && sudo apt-get install -y hub`
* Brew formulae were sharded in https://github.com/Homebrew/homebrew-core/pull/139592
@haroon-sheikh @zabil do you know if the rest of the [release workflows](https://github.com/getgauge/gauge/actions/runs/6652744383) are idempotent and can be re-run? (pypi, npm, choco)
(_edit_: I **think** I can probably just …
> Fix Gauge release brew+Github workflows

- build/brew/brew_update.rb
Brew release fails to bump the URL properly as the source code ref is incorrect.
> Fix URL in Brew release

- go.mod
- go.sum
- version/version.go
The getgauge/common upgrade solves the issue
where the gauge server crashes whenever a project is loaded that uses the ts plugin.
The cause is described here https://github.com/getgauge/gauge/issues/2419
This commit closes / permanently fixes issues like
https://github.com/getgauge/gauge-vscode/issues/735 https://github.com/getgauge/gauge-vscode/issues/636 https://github.com/getgauge/gauge-vscode/issues/885
> Upgrade getgauge/common to solve typescript server crash issue

- build/download.sh
The current download script is always downloading the [latest](https://github.com/getgauge/gauge/blob/62b9937c03b9d29d2e9f94c0778defce9afc6c4c/build/download.sh#L16) available release.
This MR adds the optional possibility to specify the version you want to install explicitly. The version defaults to `latest` , if its not provided.
```
--version=v1.5.6
```
> feat: add version parameter for download script

- .github/workflows/release.yml
The Chocolatey packages are stuck in moderation since they currently download/install packages without checksums: https://community.chocolatey.org/packages/gauge/1.5.7 
> Package automation scripts download a remote file without validating the checksum.
This change makes the Windows packages available to the Choco package release step, since the checksums don't seem to be in some other metadata.
Checksums are mandatory within Chocolatey packages now so these are needed to be able to generate the package install script. Dependent on https://github.com/getgauge/chocolatey-packages/commit/406b9d7614163c6f21de723737bd3e028783df34 which computes the checksums and changes the templating of the package accordingly, so you get a `chocolateyInstall.ps1` like
```powershell
$packageName = 'gauge' …
```
> Fix chocolatey package releases

- .github/workflows/release.yml
PyPi now requires use of API tokens (and 2FA for the user that generates them). https://blog.pypi.org/posts/2024-01-01-2fa-enforced/
Steps needed
> Fix PyPi release

- cmd/validate.go
- version/version.go
Relates to https://github.com/getgauge/gauge/issues/2244
- Adds the option to specify env for validate so that it can use the correct gauge_data_dir for validating the specs.
**Note:**
We cannot filter the validation by tags because to filter the specs, we have to parse them which in return throws the validation errors.
> Adds the option to specify env for validate

- cmd/list.go
- cmd/list_test.go
- cmd/mockRunner.go
- filter/specItemFilter.go
- version/version.go
usage: gauge list --steps
fixes #2432 
> add support to print list of implemented steps

- .github/workflows/release.yml
Last release [didn't go through](https://github.com/getgauge/gauge/actions/runs/11028707276/job/30629634452); Sourceforge have changed the way their downloads work and the Chrome UserAgent is causing it to think there is a browser and use a cookie+javascript approach rather than normal redirects.
This also upgrades to latest NSIS (`3.10`)
> Correct NSIS downloads for Windows package

- api/lang/server.go
- cmd/format.go
- config/settings.go
- formatter/formatSpecification.go
- formatter/formatter.go
- formatter/formatter_test.go
- version/version.go
1. Added a flag that makes it optional if you want the formatter to add empty lines around tags & before table definitions in the spec-files.
2. Implementation in server to handle requests from extension regarding changes in settings.json, where you can define the formatters behavior.
3. settings.go hold the 'state' of settings on the server-side, which can extended to hold any other settings added in the future.
To make it work fully a few lines needs to be in the VSC Extension as well, but I hold that until I know if this will be considered.
Further description in issue:
https://github.com/getgauge/gauge/issues/2693
> Added logic adding/not adding empty lines when formatting specs based on flag/settings.

- api/lang/format.go
- formatter/formatter.go
- version/version.go
This PR: https://github.com/getgauge/gauge/pull/2566 implemeted the possiblity for format .cpt-files, but only from cmd, no binding via LSP was added. This adds it.
Originally related to: https://github.com/getgauge/gauge/issues/1509
@sriv Can you please merge?
> Enabling formatting of .cpt files in IDE/VSC.

- build/make.go
CGO cross-compile was enabled in a8365f4ed7e63424f35f3c92dfe9d518555f6491 10 years ago, but without any comment as to why it was needed and no obvious commits around the same time - perhaps Windows native compilation was much less stable at the time (Golang `1.4` era)?
I'm not sure it is necessary anymore, so probably better to remove? WDYT @sriv?
> Don't compile with CGO for Windows

- api/lang/format.go
- api/lang/format_test.go
- execution/parallelExecution.go
- parser/conceptParser.go
- parser/conceptParser_test.go
- version/version.go
As discussed in https://github.com/getgauge/gauge/issues/2749#issuecomment-2894689848 the impl in #2700 doesn't seem correct when applying formatting to a file pre-save.
It's formatting the file as it is currently on disk and thus removing all the user's edits.
Added tests for formatting concepts in https://github.com/getgauge/gauge-lsp-tests/commit/1f045976c906d78c9c99dbc0096c547b1634fe3b and formatting unsaved specs/concepts in https://github.com/getgauge/gauge-lsp-tests/commit/136f1e0ae2eef1629992c92a3ccfce31f3901364
> Ensure LSP/IDE concept formatting works with unsaved file content

- execution/parallelExecution.go
- execution/parallelExecution_test.go
- version/version.go
Fixes #2747 
- should fix for both the "legacy" parallel and the multithreaded grpc case
Not really sure I know what I am doing here or what the consequences might be of this, but this does seem to work in both cases.
Would probably be better to have separate implementations for producing the final suiteResult between the two styles as the `aggregateResults` code path is clearly intended for the original legacy design.
> Aggregate pre+post hook messages and screenshots from parallel tests
