getgauge/gauge

- README.md
This PR cleans up indentation inconsistencies, but it's primary purpose is to check if [Snap CI's PR integration](https://snap-ci.com/github_repositories/getgauge/gauge/pulls) works.
> Make indentation and spacing consistent in README

- build/install/install.sh
The only functional change is to set `PATH` and `GAUGE_ROOT` independently.
> Tidy up install script

- build/install/install.sh
Separated interactive and non-interacticve inastallation.
Verifying if user want to install gauge at a new location
Use GAUGE_ROOT as GAUGE_PREFIX for backword compatibility.
> Update install script #599.

- execution/execute.go
- execution/parallelExecution.go
- execution/scenarioExecutor.go
- execution/simpleExecution.go
- execution/specExecutor.go
- execution/specExecutor_test.go
- execution/stepExecutor.go
- plugin/handler.go
- plugin/plugin.go
also added a few tests, some refactoring
> init spec datastore only once per spec, for #656

- cmd/install.go
- cmd/update.go
- gauge.go
- plugin/install/install.go
- projectInit/init.go
- util/httpUtils.go
> clean up console output on update, #696

- Godeps/Godeps.json
- build/analytics/dump.go
generates monthly export of Google Analytics data. 
published at https://insights.getgauge.io
> add build support for analytics export

- build/install/windows/gauge-install.nsi
- add custom page for telemetry off option
- set `/TELEMETRY off` to turn it off via silent install
> add option to disable telemetry via windows installer

- build/install/install.sh
Solving #751 
```bash
$ plugins_list=(html-report java)
$ echo "$plugins_list"                                                                          
html-report
$ echo "${plugins_list[@]}"
html-report java
```
> Send all items instead of first one

- reporter/jsonConsole.go
- reporter/jsonConsole_test.go
listening StepEnd even and caching steps corresponding to current
scenario.
> Showing step line no in JSON logger #getgauge/intellij-plugin120

- api/lang/codeAction.go
- api/lang/codeAction_test.go
- api/lang/codeLens.go
- api/lang/codeLens_test.go
- api/lang/customResponses.go
- api/lang/customResponses_test.go
- api/lang/references.go
- api/lang/references_test.go
- api/lang/server.go
- api/lang/symbols.go
- api/lang/symbols_test.go
for #879 
- adds documents symbols support
- adds workspace symbols support
> 879 symbols lsp

- Godeps/Godeps.json
- api/lang/codeAction_test.go
- api/lang/customResponses_test.go
- cmd/cmd.go
- cmd/daemon.go
- cmd/docs.go
- cmd/format.go
- cmd/refactor.go
- cmd/run.go
- cmd/run_test.go
- cmd/validate.go
- execution/rerun/rerun.go
- execution/rerun/rerun_test.go
- vendor/github.com/getgauge/common/common.go
* Reverted the previous implementation which was saving Items
* We are saving the previously executed command given the user for repeat
> Adding Repeat Last Command Feature #862

- cmd/cmd.go
- cmd/config.go
- cmd/daemon.go
- cmd/docs.go
- cmd/format.go
- cmd/init.go
- cmd/refactor.go
- cmd/run.go
- cmd/telemetry.go
- cmd/uninstall.go
- cmd/update.go
- cmd/validate.go
- removes use of logger.fatalf when command usage is incorrect.
> Handling CLI errors

- api/lang/_testdata/dummyFile.txt
- api/lang/customResponses.go
- api/lang/customResponses_test.go
- api/lang/file.go
- api/lang/server.go
- util/fileUtils.go
* Tests added for Stub Implementation API
* Saving files before new implementation stub is put into file content
> Stub impl tests

- api/lang/diagnostics.go
- api/lang/logger.go
- api/lang/server.go
- execution/execute.go
- gauge.go
- parser/parse.go
- plugin/install/check.go
- reporter/reporter.go
- track/track.go
Handling panics. Outputs to the CLI in error log format.
For lsp only a message is output.
> Handling panic better. #960

- api/lang/diagnostics.go
- api/lang/diagnostics_test.go
- validation/validate.go
- validation/validation_test.go
- Changed the way we were handling validation errors when a concept with unimplemented step is used in multiple specs.
- Have done a bit of refactoring in diagnostics.go.
> Fixing network connection closed error getgauge/gauge-js#136

- conceptExtractor/conceptExtractor.go
- formatter/formatter.go
- formatter/formatter_test.go
- gauge/step.go
- gauge/step_test.go
Using arg name instead of value for dynamic params
> Replacing dynamic and table param names

- api/infoGatherer/specDetails.go
- api/lang/completion_test.go
- api/lang/server.go
> Added custom lsp request to get specification dirs.

- cmd/cmd.go
- execution/execute.go
- logger/logger.go
- logger/logger_test.go
- reporter/jsonConsole.go
- telemetry message
- plugin's stdout
- run statistics
> fix machine-readable output

- cmd/init.go
- cmd/install.go
- cmd/run.go
- cmd/update.go
- execution/execute.go
- logger/logger.go
- plugin/install/install.go
- projectInit/init.go
- reporter/jsonConsole.go
- skel/plugin.go
handle plugin installation during execution to be machine readable
fix escaping of messages for json
> 1126 machine readable install

- parser/lex.go
- parser/lex_test.go
handle if a concept appears immediately after a step.
> spec underline is not read as step text, #1177

- .gitignore
- build/pip/MANIFEST.in
- build/pip/ReadMe.md
- build/pip/setup.py
this is a setup.py script which is completely custom written in order to download the latest release of gauge-cli or will have the ability to install an older version of gauge cli
Please review it and advise in case of any changes/enhancements needed further
Updates #1180
> ENH:PIP Installer for gauge-cli

- conn/connectionHandler.go
- execution/parallelExecution_test.go
- execution/specExecutor_test.go
- runner/grpcRunner.go
- runner/runner.go
- validation/validation_test.go
second attempt on #1158, and this should also address #1243
> 1158 exit on runner crash

- cmd/daemon.go
- track/track.go
https://github.com/getgauge/gauge-vscode/issues/293
> Track running daemon for active usage

- config/configuration.go
- config/formatter_test.go
- config/properties.go
- config/properties_test.go
- plugin/install/check.go
- plugin/install/check_test.go
* Remove gauge_update_url properties
* Extracting the version from GitHub release URL.
> Fix check for gauge update 

- gauge.go
> Add system exit code for incorrect command line arguments(#1324)

- plugin/handler.go
- send message to pluigns without capabilites first
- chunk the data after that and send to all pluings with capabilites to chunk
> xml-report/#16 Fix report missing data

- cmd/cmd.go
- cmd/run_test.go
Gauge Returns Exit Code 0 When It Fails To Run #1405
> changed exit code from 0 to 1 for all cases

- cmd/run_test.go
- formatter/formatter.go
- formatter/formatter_test.go
- reporter/reporter.go
parameters are now showed in the verbose console #1413
> show parameters in console #1413

- logger/gaugeLogger.go
- logger/logWriter.go
- logger/logger.go
- logger/logger_test.go
logger to print messages to stdout according to log level for Gauge and plugins. #216.
Fixes fatal log aggregation syntax, #1426
> Refatoring logger and plugin log writer

- logger/logWriter.go
> Read log line by line.

- .github/issue_template.md
- CONTRIBUTING.md
- logger/logger.go
- logger/logger_test.go
- vendor/github.com/getgauge/common/CONTRIBUTING.md
Modify the support links to point to spectrum
> Remove gitter and point to spectrum for chat and support

- .github/workflows/tests.yml
- plugin/plugin.go
> remove GRPC_STATUS_UNAVAILABLE noise when plugin is shutting down, #1560

- execution/merge.go
- execution/result/result.go
- execution/result/suiteResult.go
- execution/scenarioExecutor.go
- execution/simpleExecution.go
- execution/simpleExecution_test.go
- execution/specExecutor.go
- execution/stepExecutor.go
- gauge/protoConverters.go
Fixes getgauge/html-report#247
> Accept screenshot data from runners without screenshot writer

- build/install/windows/gauge-install.nsi
> Remove creation of un-necessary temp dir.

- build/create_release_text.rb
This ruby file displays a list of features and bugs merged after
the last release.
It uses the github api to search for pull requests labelled
"feature" or "bug" and prints a markdown friendly output
that can be posted as release notes.
Example usage
ruby create_release_text.rb getgauge gauge
> Display pull requests between releases

- .github/workflows/tests.yml
- execution/merge.go
- execution/merge_test.go
- version/version.go
> Fix for mismatch of steps and table names in report

- logger/logWriter.go
- logger/logWriter_test.go
Signed-off-by: BugDiver <vinaysh@thoughtworks.com>
Fixes #1642
> Remove carriage returns #1642

- logger/logWriter.go
Signed-off-by: BugDiver <vinaysh@thoughtworks.com>
> Use bufio.Scanner to handle new lines.

- cmd/cmd.go
- cmd/telemetry.go
- cmd/version.go
- execution/parallelExecution.go
- projectInit/init.go
- util/util.go
- validation/suggest.go
> Printing console messages via logger package #1542

- build/brew/create_brew_pr.sh
Pull requests and commits should be in the form of: `formula version`.
> Strip `v` prefix from brew commit and PR title

- build/create_release_text.rb
> Update latest release GitHub api

- execution/parallelExecution.go
> Add check for spec length in filtered execution #1704

- execution/merge.go
- execution/merge_test.go
> Add pre/post spec messages to result when merging tables #1676

- api/lang/runner.go
- api/lang/server.go
Fixes https://github.com/getgauge/gauge-vscode/issues/439
> Fix error message for lsp server.

- build/create_release_text.rb
> Update query param and set header to fix api version

- .github/workflows/release.yml
> update url for nsis

- .github/workflows/release.yml
> Set userAgent for downloading from sourceForge

- .github/workflows/release.yml
> fix user agent format

- .github/workflows/release.yml
> Add cmd to import types

- .github/workflows/auto_rebase_prs.yml
- README.md
Current link to user doco is broken on readme
> Fix broken user doco link on readme

- execution/specExecutor.go
Signed-off-by: BugDiver <vinaysh@thoughtworks.com>
> Resolving special params in scenario data table #1746

- formatter/formatter.go
- formatter/formatter_test.go
> fix step formatting for dynamic params, fixes 1767

- util/_testSpecDir/foo.cpt
- util/fileUtils.go
- util/fileUtils_test.go
- version/version.go
> Search for concepts in custom spec dirs as well

- conceptExtractor/conceptExtractor_test.go
> Fix formatting related test failures

- .github/workflows/release.yml
Signed-off-by: BugDiver <vinaysh@thoughtworks.com>
> Use GITHUB_PATH and GITHUB_ENV.

- .github/workflows/release.yml
> remove use of hub action

- util/fileUtils.go
- util/fileUtils_test.go
> Remove duplicate concept file entries

- .github/ISSUE_TEMPLATE/config.yml
- CONTRIBUTING.md
- README.md
- logger/logger.go
- logger/logger_test.go
> Refer the new discussion forum

- build/make.go
- version/version.go
Here is my PR for linux-arm64 as result from the [discussions](https://github.com/getgauge/gauge/discussions/2035).
> Added support for Linux arm64

- runner/runner.go
- version/version.go
Signed-off-by: Pavol Pitonak <pavol@pitonak.com>
> fix typo in runner.go

- CONTRIBUTING.md
- README.md
Add status of the project to that users and contributors are aware.
Related to: https://github.com/getgauge/gauge/issues/1732
> Add support notice section

- build/brew/create_brew_pr.sh
Signed-off-by: Haroon Sheikh <haroon.sheikh@outlook.com>
> Replacing deprecated hub with gh cli

- .github/dependabot.yml
Signed-off-by: Haroon Sheikh <haroon.sheikh@outlook.com>
> Fixing indentation in dependabot.yml

- .github/workflows/release.yml
- .github/workflows/tests.yml
- version/version.go
Also trigger a release on updated dependencies.
> Test with Node 22
